using System.Collections.Generic;
using NeptuneEvo.BattlePass.Models;
using NeptuneEvo.Chars.Models;

namespace NeptuneEvo.BattlePass.Season3Models
{
    public static class Repository
    {
               
        public static readonly List<BattlePassTask> BattlePassTask = new List<BattlePassTask>
        {
	        new BattlePassTask(0, "Принять участие в Gun Game", 1, 30, "Пойдем выйдем", "Необычное задание", 777, BattlePassRewardDiff.Medium),
			new BattlePassTask(1, "Купить модификацию на оружие в Gun Shop", 1, 30, "Кастомизация оружия", "Лёгкое задание", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(2, "Проехать 5 миль с пассажиром, будучи таксистом", 5, 30, "Таксист Младший", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(3, "Сыграть в сапера (F9)", 1, 30, "Bomb has been defused", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(4, "Cыграть на игровых автоматах в казино", 1, 30, "Три топора", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(5, "Пополнить банковский счет на 10$ через банкомат", 1, 30, "Деньжата", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(6, "Купить лотерейный билет в 24/7", 1, 30, "Везунчик?", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(7, "Реанимировать человека с помощью аптечки", 1, 30, "I need a medic!", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(8, "Купить любую одежду в Clothes Shop", 1, 30, "Модный приговор", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(9, "Устроиться на начальную работу (в мэрии)", 1, 30, "Опять работать..", "Лёгкое задание", 420, BattlePassRewardDiff.Easy),
			new BattlePassTask(10, "Уволиться с начальной работы (в мэрии)", 1, 30, "Выходной...", "Лёгкое задание", 333, BattlePassRewardDiff.Easy),
			new BattlePassTask(11, "Подать 3 объявления в NEWS через телефон", 3, 30, "Меня услышат все!", "Лёгкое задание.", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(12, "Починить транспорт с помощью гаечного ключа", 1, 30, "Гаечный ключ", "Лёгкое задание.", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(13, "Починить транспорт на метке починки на респавне механиков", 1, 30, "Машину мне почини!", "Необычное задание", 250, BattlePassRewardDiff.Medium),
			new BattlePassTask(14, "Передать кому-нибудь деньги", 1, 30, "Маме деньги неси!", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(15, "Купить таблетку у врача в EMS", 1, 30, "Врача!!!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(16, "Скинуть на пол любой предмет", 1, 30, "Закладка", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(17, "Поднять с пола любой предмет", 1, 30, "Залутал", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(18, "Сделать татуировку на любой части тела", 1, 30, "Кольщик, наколи мне...", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(19, "Заправить 20 литров топлива на АЗС", 1, 30, "В бак мне залей", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(20, "Отвезти 10 посылок, работая почтальоном", 9, 30, "Вам почта!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(21, "Проехать 20 меток, работая газонокосильщиком", 20, 30, "Гонщик нелегальный", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(22, "Починить 20 электроблоков, работая электриком", 20, 30, "Фиксик", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(23, "Запустить фейерверк", 1, 30, "Моё искусство - это взрыв!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(24, "Приехать на вызов, работая механиком", 1, 30, "Педаль в пол", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(25, "Зайти в любой дом, кроме своего", 1, 30, "Домушник", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(26, "Арендовать любой транспорт", 1, 30, "Каршеринг", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(27, "Помыть транспорт в автомойке", 1, 30, "Мойдодыр", "Лёгкое задание", 666, BattlePassRewardDiff.Easy),
			new BattlePassTask(28, "Купить любой фейерверк", 1, 30, "Деньги на ветер", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(29, "Купить пиво в 24/7", 1, 30, "Светлое нефильтрованное будущее...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(30, "Использовать парную анимацию", 1, 30, "Взаимодействие - наше всё.", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(31, "Отыграть что-нибудь в РП-чат (/me)", 1, 30, "Ролеплейщик", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(32, "Пожать руку 3 людям", 3, 30, "Будем знакомы", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(33, "Провести тест-драйв любого транспорта", 1, 30, "Оценим от 1 до 10", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(34, "Купить любую маску в Mask Shop", 1, 30, "Масочник", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(35, "Поучаствовать в уличной гонке", 1, 30, "Давно тебя не было в уличных гонках", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(36, "Подарить любовную записку через трейд", 1, 30, "Знаки внимания", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(37, "Передать пиво через трейд", 1, 30, "Поделись пивком с ближним!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(38, "Посетить охотничий магазин", 1, 30, "На отшибе", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(39, "Воспользоваться любым банкоматом", 1, 30, "Введите пароль", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(40, "Заправить автомобиль на заправке", 1, 30, "Полный бак!", "Лёгкое задание", 350, BattlePassRewardDiff.Easy),
			new BattlePassTask(41, "Передать кому-нибудь Револьвер", 1, 30, "Гони ревик", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(42, "Заправить транспорт из канистры", 1, 30, "Залей бензинчика", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(43, "Купить информацию о доме в риэлторском агентстве", 1, 30, "Ловец со стажем", "Сложное задание", 2228, BattlePassRewardDiff.Hard),
			new BattlePassTask(44, "Купить что-нибудь в LS Customs", 1, 30, "Тачку на прокачку", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(45, "Купить связку ключей в 24/7", 1, 30, "Ключник", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(46, "Эвакуировать любой автомобиль в гараж", 1, 30, "Само-эвакуаторщик", "Сложное задание", 444, BattlePassRewardDiff.Hard),
			new BattlePassTask(47, "Арендовать палатку на рынке", 1, 30, "Продаван", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(48, "Купить что-нибудь на рынке", 1, 30, "Покупан", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(49, "Продлить аренду палатки на рынке", 1, 30, "Настоящий торгаш!", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(50, "Открыть любой кейс", 1, 30, "Испытай удачу", "Сложное задание", 250, BattlePassRewardDiff.Hard),
			new BattlePassTask(51, "Вызвать гос.сотрудника с помощью NPC", 1, 30, "Мне нужна помощь!", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(52, "Передать пиццу через трейд ", 1, 30, "Поделись пиццей с ближним!", "Необычное задание", 444, BattlePassRewardDiff.Medium),
			new BattlePassTask(53, "Сделать покупку в Barber Shop", 1, 30, "Привет, подстрижися", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(54, "Передать кому-нибудь наркотики", 1, 30, "Кизяка", "Сложное задание", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(55, "Сыграть в казино", 1, 30, "Еб***** рот этого казино!", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(56, "Повторить чью-нибудь анимацию через G-меню", 1, 30, "Повторюшка", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(57, "Купить что-либо в охотничьем магазине", 1, 30, "Отдалённый магазинчик...", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(58, "Отремонтировать 3 автомобиля, работая механиком", 3, 30, "Старший механик", "Сложное задание", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(59, "Проехать 15 миль с пассажирами, работая таксистом", 15, 30, "Старший бомбила", "Сложное задание", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(60, "Получить PayDay", 1, 30, "ЗПха-то капает!", "Лёгкое задание", 420, BattlePassRewardDiff.Easy),
			new BattlePassTask(61, "Покушать чипсов", 1, 30, "Ням-ням чипсеки..", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(62, "Вызвать такси 2 раза", 2, 30, "ТАКСИИИИИИИ!", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(63, "Прокатиться на автобусе и заплатить за проезд", 1, 30, "Передаем за проезд", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(64, "Проехать 20 меток на работе водителя автобуса", 20, 30, "Поворот не туда", "Сложное задание", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(65, "Вызвать механика", 1, 30, "Чини!", "Лёгкое задание", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(66, "Выпить пивка", 1, 30, "Не 'Пиво' а 'Пыво'", "Лёгкое задание", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(67, "Покурить кальян 3 раза", 3, 30, "Дудка дьявола", "Сложное задание", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(68, "Сделать 5 затяжек вейпа", 5, 30, "Вейп не курят, а парят", "Необычное задание", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(69, "Покурить бонг", 1, 30, "На часах 4:20...", "Необычное задание", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(70, "Использовать любую анимацию 3 раза", 3, 30, "Шоу танцы", "Лёгкое задание", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(71, "Разочек курнуть вейпа", 1, 30, "Миссис Пафф..", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(72, "Совершить трейд с другим игроком", 1, 30, "Функциональный обмен", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(73, "Положить ключ в связку ключей", 1, 30, "У тебя больше двух машин?", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(74, "Использовать голосовую рацию", 1, 30, "Пшшш... Как слышно?", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(75, "Подарить розу через трейд", 1, 30, "Миллион миллион миллион.... Алых роз!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(76, "Записать номер телефона в контакты", 1, 30, "ВКонтакте", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(77, "Написать 3 SMS кому-либо, кто находится 'в сети'", 3, 30, "Общение - ключ к успеху", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(78, "Отредактировать имеющийся контакт в телефоне", 1, 30, "Алло, вы шо?", "Сложное задание", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(79, "Отыграть что-нибудь в /do", 1, 30, "Взгляд со стороны", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(80, "Прошептать что-нибудь (/w)", 1, 30, "Я прошепчу тебе на ушко 'Аннигиляторная пушка'", "Необычное задание", 250, BattlePassRewardDiff.Medium),
			new BattlePassTask(81, "Крикнуть что-нибудь (/s)", 1, 30, "Дай шуму", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(82, "Отыграть что-нибудь в /try", 1, 30, "Орёл/Решка", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(83, "Расставить машины в гараже с помощью функциональной парковки", 1, 30, "Перфекционист", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(84, "Поговорить с NPC в полицейском участке", 1, 30, "This is the police", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(85, "Поговорить с NPC в больнице", 1, 30, "Медицинские рекомендации", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(86, "Пристегнуть ремень безопасности", 1, 30, "Ай болит", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(87, "Открыть капот транспортного средства", 1, 30, "Автомеханик", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(88, "Залезть в багажник автомобиля", 1, 30, "В лес", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(89, "Указать пальцем куда-нибудь 3 раза", 3, 30, "Где?", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(90, "Положить предмет в багажник", 1, 30, "Клад на колёсах", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(91, "Отремонтировать автомобиль, работая механиком", 1, 30, "Механик", "Сложное задание", 444, BattlePassRewardDiff.Hard),
			new BattlePassTask(92, "Доставить 10 сумок с деньгами, работая инкассатором", 10, 30, "Везу деньги бумажные", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(93, "Написать рекламу на асфальте (/action)", 1, 30, "Рекламщик 228", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(94, "Вылечить себя с помощью аптечки", 1, 30, "Лови аптечку", "Необычное задание", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(95, "Накатать 10 миль, будучи пассажиром такси", 10, 30, "Яндекс.Такси", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(96, "Получить дубликат ключей от автомобиля", 1, 30, "Смена замков", "Сложное задание", 555, BattlePassRewardDiff.Hard),
			new BattlePassTask(97, "Поговорить с любым квестовым персонажем", 1, 30, "Болтун", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(98, "Начать лечение в больнице на метке", 1, 30, "Лечи меня полностью!", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(99, "Использовать предмет с помощью быстрого слота", 1, 30, "На диком западе...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(100, "Отыграть что-нибудь в /todo", 1, 30, "Отыгровщик", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(101, "Показать паспорт кому-нибудь", 1, 30, "Papers, Please", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(102, "Кинуть кости в казино (/dice)", 1, 30, "Игроман", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(103, "Купить лом в 24/7", 1, 30, "Взломщик", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(104, "Купить фонарик в 24/7", 1, 30, "Во тьме ночной, при свете дня...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(105, "Купить гаечный ключ в 24/7", 1, 30, "Бегу, отец!", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(106, "Купить молоток в 24/7", 1, 30, "Забиваем гвозди", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(107, "Купить чипсы в 24/7", 1, 30, "Ммм чипсеки", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(108, "Купить пиццу в 24/7", 1, 30, "Хочу пицу...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(109, "Купить канистру в 24/7", 1, 30, "Нужда каждого водителя!", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(110, "Купить любовную записку в 24/7", 1, 30, "Дела любовные", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(111, "Купить бинокль в 24/7", 1, 30, "Высоко сижу, далеко гляжу...", "Лёгкое задание", 2222, BattlePassRewardDiff.Easy),
			new BattlePassTask(112, "Купить вейп в 24/7", 1, 30, "Vape Nation", "Лёгкое задание", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(113, "Купить зонтик в 24/7", 1, 30, "А вдруг дождь?", "Лёгкое задание", 555, BattlePassRewardDiff.Easy),
			new BattlePassTask(114, "Купить гитару в 24/7", 1, 30, "Гитарист", "Лёгкое задание", 1111, BattlePassRewardDiff.Easy),
			new BattlePassTask(115, "Купить камеру в 24/7", 1, 30, "Блогер?", "Лёгкое задание", 1500, BattlePassRewardDiff.Easy),
			new BattlePassTask(116, "Купить микрофон в 24/7", 1, 30, "Пусть услышат все!", "Лёгкое задание", 1111, BattlePassRewardDiff.Easy),
			new BattlePassTask(117, "Купить мячик в 24/7", 1, 30, "Баскетбол ногой", "Лёгкое задание", 444, BattlePassRewardDiff.Easy),
			new BattlePassTask(118, "Купить бургер в Burger-Shot", 1, 30, "Заказ Биг Смоука", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(119, "Купить хот-дог в Burger-Shot", 1, 30, "Булочка с сосиской...", "Лёгкое задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(120, "Выкинуть 'удачно' через /try", 1, 30, "Удача на твоей стороне", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(121, "Купить Sprunk в Burger-Shot", 1, 30, "Почти как Спрайт...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(122, "Передать кому-нибудь хот дог", 1, 30, "Поделись сосиской с ближним!", "Необычное задание", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(123, "Передать кому-нибудь Бесплатный кейс", 1, 30, "Подарки - это важно", "Сложное задание", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(124, "Открыть дом", 1, 30, "Жду гостей", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(125, "Закрыть дом", 1, 30, "Не жду гостей", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(126, "Передать метку водителю, будучи пассажиром", 1, 30, "Вези меня туда!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(127, "Купить сэндвич в Burger-Shot", 1, 30, "Бургер Кинг", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(128, "Купить eCola в Burger-Shot", 1, 30, "Пепсикольный", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(129, "Посети и изучи любой GunShop", 1, 30, "Местная википедия", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(130, "Купить любое оружие в GunShop", 1, 30, "На забив", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(131, "Передать кому-нибудь ключ для починки авто", 1, 30, "Ключ от сердца моего...", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(132, "Скушать пиццу", 1, 30, "Ммм гавайская...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(133, "Скушать сендвич", 1, 30, "Сабвей отдыхает!", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(134, "Выпить Sprunk", 1, 30, "Освежает...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(135, "Скушать хот-дог", 1, 30, "Булочка с сосиской", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(136, "Выпить e-Cola", 1, 30, "Кока", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(137, "Курнуть косячок (использовать наркотики)", 1, 30, "4:20", "Необычное задание", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(138, "Скушать бургер", 1, 30, "Еду в магазин Гуччи в Санкт-Петербурге", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(139, "Передать e-Cola через трейд", 1, 30, "Поделись кокой!", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(140, "Передать Sprunk через трейд", 1, 30, "Освежи друга", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(141, "Передать бургер через трейд", 1, 30, "Доставочка для друга", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(142, "Передать сендвич через трейд", 1, 30, "Поделись сендвичем!", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(143, "Передать аптечку через трейд", 1, 30, "Полечись, бро", "Необычное задание", 222, BattlePassRewardDiff.Medium),
			new BattlePassTask(144, "Передать записку через трейд", 1, 30, "Весточка", "Сложное задание", 222, BattlePassRewardDiff.Hard),
			
        };
//free призы
		public static List<BattlePassReward> BattlePassAwards = new List<BattlePassReward>
		{
		new BattlePassReward(1, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(2, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(3, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(4, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(5, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(8, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
		new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 2),
		new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Cheburek", name:"[GTA]RUNE Cheburek", count: 1),
		new BattlePassReward(11, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(12, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(13, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(14, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 2),
		new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "961_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "984_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(16, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"panto", name:"[GTA]Benefactor Panto", count: 1),
		new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(19, type: BattlePassRewardType.Donate, count: 950),
		new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Jewelry, count: 1, data: "319_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Jewelry, count: 1, data: "267_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(22, type: BattlePassRewardType.Donate, count: 1500),
		new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Musket, count: 1),
		new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(26, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(29, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Burrito", name:"[GTA]Declasse Burrito", count: 1),
		new BattlePassReward(31, type: BattlePassRewardType.Donate, count: 1500),
		new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 3),
		new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 3),
		new BattlePassReward(34, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 3),
		new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 3),
		new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 3),
		new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 3),
		new BattlePassReward(38, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 3),
		new BattlePassReward(39, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Stretch", name:"[GTA]Dundreary Stretch", count: 1),
		new BattlePassReward(41, type: BattlePassRewardType.Money, count: 500000),
		new BattlePassReward(42, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(43, type: BattlePassRewardType.Donate, count: 1200),
		new BattlePassReward(44, type: BattlePassRewardType.Donate, count: 1300),
		new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"mark2", name:"[RL]Karin Marco", count: 1),
		new BattlePassReward(46, type: BattlePassRewardType.Money, count: 500000),
		new BattlePassReward(47, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(48, type: BattlePassRewardType.Donate, count: 1300),
		new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(51, type: BattlePassRewardType.Money, count: 500000),
		new BattlePassReward(52, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(53, type: BattlePassRewardType.Donate, count: 1300),
		new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 4),
		new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
		new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1),
		new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(59, type: BattlePassRewardType.Money, count: 330000),
		new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Glendale", name:"[GTA]Benefactor Glendale", count: 1),
		new BattlePassReward(61, type: BattlePassRewardType.Donate, count: 1300),
		new BattlePassReward(62, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(63, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(64, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 2),
		new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
		new BattlePassReward(67, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1),
		new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavyRifle, count: 1),
		new BattlePassReward(71, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(73, type: BattlePassRewardType.Donate, count: 13000),
		new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
		new BattlePassReward(75, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Stafford", name:"[GTA]Enus Stafford", count: 1),
		new BattlePassReward(76, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(78, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(79, type: BattlePassRewardType.Money, count: 200000),
		new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
		new BattlePassReward(81, type: BattlePassRewardType.Donate, count: 10000),
		new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(83, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(84, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(86, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(87, type: BattlePassRewardType.Money, count: 200000),
		new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
		new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 3),
		new BattlePassReward(90, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"bmwe39", name:"[RL]Ubermacht 5-line A39", count: 1),
		new BattlePassReward(91, type: BattlePassRewardType.Donate, count: 10000),
		new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(93, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(96, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(97, type: BattlePassRewardType.Money, count: 200000),
		new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
		new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 3),
		new BattlePassReward(100, type: BattlePassRewardType.Donate, count: 25000),
		new BattlePassReward(101, type: BattlePassRewardType.Donate, count: 10000),
		new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(103, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(107, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(108, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(110, type: BattlePassRewardType.Donate, count: 1000),
		new BattlePassReward(111, type: BattlePassRewardType.Donate, count: 1000),
		new BattlePassReward(112, type: BattlePassRewardType.Donate, count: 1000),
		new BattlePassReward(113, type: BattlePassRewardType.Donate, count: 1000),
		new BattlePassReward(114, type: BattlePassRewardType.Donate, count: 1000),
		new BattlePassReward(115, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"golf7r", name:"[RL]BF Wolf 7S", count: 1),
		new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 3),
		new BattlePassReward(117, type: BattlePassRewardType.Donate, count: 1000),
		new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 3),
		new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 4),
		new BattlePassReward(120, type: BattlePassRewardType.Money, count: 600000),
		new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(123, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(125, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case10, count: 1),
		new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
		new BattlePassReward(129, type: BattlePassRewardType.Money, count: 200000),
		new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"octavia18", name:"[RL]BF Olivia GS", count: 1),
		new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.PrecisionRifle, count: 1),
		new BattlePassReward(132, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(133, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(134, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 2),
		new BattlePassReward(135, type: BattlePassRewardType.Money, count: 25000000),
		new BattlePassReward(136, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(137, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(138, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(139, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(140, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(141, type: BattlePassRewardType.Item, itemId: (int)ItemId.Musket, count: 1),
		new BattlePassReward(142, type: BattlePassRewardType.Donate, count: 1000),
		new BattlePassReward(143, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(144, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(145, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 2),
		new BattlePassReward(146, type: BattlePassRewardType.Money, count: 25000000),
		new BattlePassReward(147, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(148, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(149, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(150, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"xts", name:"[RL]Cavalcade XDS Limo", count: 1),
		};

//prime призы
		public static List<BattlePassReward> BattlePassAwardsPremium = new List<BattlePassReward>
		{
		new BattlePassReward(1, type: BattlePassRewardType.Item, itemId: (int)ItemId.Musket, count: 1),
        new BattlePassReward(2, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Infernus", name:"[GTA]Pegassi Infernus", count: 1),
		new BattlePassReward(3, type: BattlePassRewardType.Money, count: 300000),
		new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "960_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "988_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "961_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "984_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(6, type: BattlePassRewardType.Money, count: 150000),
		new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
		new BattlePassReward(8, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Adder", name:"[GTA]Truffade Adder", count: 1),
		new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(12, type: BattlePassRewardType.Money, count: 500000),
		new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 2),
		new BattlePassReward(14, type: BattlePassRewardType.Money, count: 440000),
		new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(16, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 2),
		new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(19, type: BattlePassRewardType.Money, count: 2500000),
		new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"x6m2", name:"[RL]Ubermacht Y6 W H96", count: 1),
		new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "947_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "979_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(22, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "942_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(22, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "982_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(23, type: BattlePassRewardType.Money, count: 3500000),
		new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Ears, count: 1, data: "85_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Ears, count: 1, data: "88_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"vclass", name:"[RL]Benefactor V-Series Veto", count: 1),
		new BattlePassReward(26, type: BattlePassRewardType.Money, count: 3500000),
		new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(29, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "309_12_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(29, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "301_12_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(31, type: BattlePassRewardType.Money, count: 4500000),
		new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 4),
		new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(34, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"vclass", name:"[RL]Benefactor V-Series Veto", count: 1),
		new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"xk", name:"[RL]Buckingham xk", count: 1),
		new BattlePassReward(38, type: BattlePassRewardType.Money, count: 4500000),
		new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "404_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "428_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(41, type: BattlePassRewardType.Money, count: 4500000),
		new BattlePassReward(42, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"terzo", name:"[RL]Pegassi Tenzo", count: 1),
		new BattlePassReward(46, type: BattlePassRewardType.Money, count: 6500000),
		new BattlePassReward(47, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 4),
		new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "942_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "982_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(51, type: BattlePassRewardType.Money, count: 2500000),
		new BattlePassReward(52, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
		new BattlePassReward(55, type: BattlePassRewardType.Money, count: 10000000),
		new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "811_1_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "860_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(58, type: BattlePassRewardType.Money, count: 10000000),
		new BattlePassReward(59, type: BattlePassRewardType.Money, count: 20000000),
		new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"xclass2", name:"[RL]Benefactor X-Monster", count: 1),
		new BattlePassReward(61, type: BattlePassRewardType.Money, count: 10000000),
		new BattlePassReward(62, type: BattlePassRewardType.Money, count: 20000000),
		new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(66, type: BattlePassRewardType.Money, count: 20000000),
		new BattlePassReward(67, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 4),
		new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),
		new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"noire", name:"[RL]Truffade Blanche", count: 1),
		new BattlePassReward(71, type: BattlePassRewardType.Money, count: 12000000),
		new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(73, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),	
		new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(75, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"yz450f", name:"[RL]Yamaha YZ 450 F", count: 1),
		new BattlePassReward(76, type: BattlePassRewardType.Money, count: 50000000),
		new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(78, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),	
		new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
		new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"escalade2", name:"[RL]Cavalcade Excalibur MG", count: 1),
        new BattlePassReward(81, type: BattlePassRewardType.Money, count: 50000000),
		new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
		new BattlePassReward(83, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 1),	
		new BattlePassReward(84, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
		new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"ram", name:"[RL]Bravado RUM", count: 1),
		new BattlePassReward(86, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(87, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),	
		new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 4),
		new BattlePassReward(90, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(92, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(93, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),	
		new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 4),
		new BattlePassReward(96, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(98, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(99, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "444_2_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "433_2_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(101, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(103, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),	
		new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 4),
		new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "762_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "789_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(107, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(108, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"gle63", name:"[RL]Benefactor-ASG JLE S292", count: 1),
		new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(115, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "733_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(115, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "755_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 2),
		new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.GlowStick, count: 1),
		new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.PrecisionRifle, count: 1),
		new BattlePassReward(123, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
		new BattlePassReward(125, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"x5me70", name:"[RL]Ubermacht Y5 W A70", count: 1),
		new BattlePassReward(126, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(129, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Jewelry, count: 1, data: "342_0_True", gender: BattlePassRewardGender.Man),
		new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Jewelry, count: 1, data: "290_0_False", gender: BattlePassRewardGender.Woman),
		new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(132, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(133, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(134, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 2),
		new BattlePassReward(135, type: BattlePassRewardType.Money, count: 25000000),
		new BattlePassReward(136, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(137, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(138, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(139, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(140, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"touareg", name:"[RL]BF Twareg", count: 1),
		new BattlePassReward(141, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
		new BattlePassReward(142, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(143, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(144, type: BattlePassRewardType.Money, count: 5000000),
		new BattlePassReward(145, type: BattlePassRewardType.Item, itemId: (int)ItemId.Snowball, count: 2),
		new BattlePassReward(146, type: BattlePassRewardType.Money, count: 25000000),
		new BattlePassReward(147, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
		new BattlePassReward(148, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 3),
		new BattlePassReward(149, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case13, count: 3),
		new BattlePassReward(150, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"snowmobile", name:"[RL]Speedophile Snowshark", count: 1),
		};

    }
}