import { storeSettings } from 'store/settings';

const defaultSettings = {
  language: "ru",
  schat: true,
  hud: true,
  radar: true,
  ids: true,
  compass: true,
  captureHud: "dark",
  driftCounter: true,
  showHotkeys: "yes",
  speedoType: "Minimalistic_2",
  ultraWideMode: false,
  speedoUpdate: "normal",
  viewTheme: "dark",
  hitmarker: true,
  streamerMode: false,
  displayChatMsg: true,
  schatPunish: true,
  walkStyle: "normal",
  vehicleEntering: "driver_priority",
  facialAnim: "standard",
  integratedFont: "ProximaNova",
  cruiseType: "speed_limit",
  generalSoundVol: 50,
  voiceChatVol: 50,
  ambientMusicVol: 50,
  animMusicVol: 50,
  radioVol: 50,
  walkieSoundVol: 50,
  notificationVol: 50,
  voiceChatBlock: "no",
  voiceChatOffDelay: "0",
  micSensitivity: 50,
  cinemaVolume: 50,
  animMusicToggle: true,
  ambientMusicToggle: true,
  accessorySounds: true,
  navigatorVoice: true,
  radarSound: true,
  seatbeltWarn: true,
  hitmarkerSound: true,
  listeningMode: "standard",
  voiceActivationMode: "push",
  noiseSuppression: true,
  adminDeleteWeazelNews: false,
  adminDeleteMarketplace: false,
  adminBigChipsExchange: false,
  adminLargeMoneyTransfer: false,
  adminFamilyBonus: false,
  adminMassBonus: false,
  adminCaptZoneColorChange: false,
  adminFractionBonus: false,
  adminFractionFunding: false,
  adminCharacterAppearanceChange: false,
  adminCharacterNameChange: false,
  adminAntiCheatBan: false,
  adminSystemShutdown: false,
  adminAdminLeakBan: false,
  adminForbiddenAnimation: false,
  adminSuspiciousDonateActivity: false,
  adminForbiddenSoftware: false,
  adminStungunUsage: false,
  adminAimUsage: false,
  chatWidth: 500,
  chatHeight: 400,
  chatSettings: "standard",
  chatTheme: "Clean",
  chatFont: "ProximaNova",
  chatFontStyle: "Regular",
  chatBorderType: "Stroke",
  chatTimestamp: "No",
  chatFontSize: 16,
  chatFontShadow: 0,
  chatFontShadowAlpha: 0,
  chatLinesMargin: 0,
  chatLineHeight: 0,
  chatCmdsSettings: "standard",
  chatCmdsFont: "ProximaNova",
  chatCmdsFontStyle: "Regular",
  chatCmdsFontSize: 14,
  phone: ["K"],
  table: ["Tab"],
  pressI: ["I"],
  voice: ["V"],
  radio: ["R"],
  partyCreateMarker: ["B"],
  fingerPointing: ["G"],
  mainMenu: ["F5"],
  tasksMenu: ["F6"],
  reportMenu: ["F7"],
  openGarageInfo: ["G"],
  circleAnimMenu: ["H"],
  langWheel: ["L"],
  acceptRequest: ["Y"],
  denyRequest: ["N"],
  pickupItem: ["E"],
  takeItemFromHands: ["F"],
  interaction: ["E"],
  pressE: ["E"],
  driverEnter: ["F"],
  passengerEnter: ["Shift", "F"],
  toggleEngine: ["M"],
  carLock: ["L"],
  belt: ["Shift", "B"],
  gps: ["G"],
  cruise: ["C"],
  autopilot: ["Shift", "C"],
  cuff: ["Ctrl", "C"],
  followPlayer: ["F"],
  hookCuffedPlayer: ["Ctrl", "H"],
  recording: ["F10"],
  changeVisorState: ["U"],
  megaphone: ["O"],
  crouch: ["Ctrl"],
  crawl: ["X"],
  OOCMode: ["T"],
  pressF: ["F"],
  clothesAction: ["A"],
  cancelMacro: ["Esc"],
  muteMicrophone: ["Shift", "M"],
  crosshairSettings: "standard",
  crosshairColor: {
    "Основной": "#ffffff",
    "Наведение": "#ff0000"
  },
  crosshairCenter: "no",
  crosshairCentralDistance: 0,
  crosshairLineLength: 10,
  crosshairLineThickness: 2,
  crosshairIncline: 0,
  crosshairStroke: 0,
  crosshairOpacity: 1,
};

const meta = {
  language: { title: "Язык", type: "selector", list: [{ value: "ru", label: "Русский" }, { value: "en", label: "English" }] },
  schat: { title: "Чат", type: "checkbox" },
  hud: { title: "Игровой интерфейс", type: "checkbox" },
  radar: { title: "Карта", type: "checkbox" },
  ids: { title: "ID над игроками", type: "checkbox" },
  compass: { title: "Компас", type: "checkbox" },
  captureHud: { title: "Интерфейс сражения за территорию", type: "selector", list: [{ value: "dark", label: "Тёмный" }, { value: "light", label: "Светлый" }] },
  driftCounter: { title: "Дрифт очки", type: "checkbox" },
  showHotkeys: { title: "Отображение подсказок", type: "selector", list: [{ value: "no", label: "Нет" }, { value: "yes", label: "Да" }] },
  speedoType: { title: "Спидометр", type: "selector", list: [{value: "Disabled", label: "Выключен"}, { value: "Advanced_1", label: "Расширенный (1)" }, { value: "Advanced_2", label: "Расширенный (2)" }, {value: "Minimalistic_1", label: "Минималистичный (1)"}, {value: "Minimalistic_2", label: "Минималистичный (2)"},{value: "Minimalistic_3", label: "Минималистичный (3)"}] },
  ultraWideMode: { title: "Ультра широкий режим", type: "checkbox" },
  speedoUpdate: { title: "Скорость обновления спидометра", type: "selector", list: [{ value: "mental", label: "Моментально" }, { value: "fast", label: "Быстро" }, { value: "normal", label: "Нормально" },{ value: "slow", label: "Медленно" }] },
  viewTheme: { title: "Тема интерфейса", type: "selector", list: [{ value: "dark", label: "Тёмная" }, { value: "light", label: "Светлая" }] },
  hitmarker: { title: "Хитмаркер", type: "checkbox" },
  streamerMode: { title: "Режим стримера", type: "checkbox" },
  displayChatMsg: { title: "Сообщения над игроками", type: "checkbox" },
  schatPunish: { title: "Наказания в чат", type: "checkbox" },
  walkStyle: { title: "Стиль походки", type: "selector", list: [ { value: "normal", label: "Стандартный" }, { value: "proud", label: "Гордый" }, { value: "confident", label: "Уверенный" }, { value: "drunk", label: "Пьяный" },  { value: "fast", label: "Быстрый" },  { value: "slow", label: "Медленный" },   { value: "fat", label: "Толстый" }, { value: "gangster", label: "Гангстер" }, { value: "hasty", label: "Торопливый" }, { value: "injured", label: "Раненый" }, { value: "timid", label: "Пугливый" }, { value: "sad", label: "Печальный" }, { value: "tough", label: "Жесткий" }, { value: "showoff", label: "Хвастун" }, { value: "tramp", label: "Бродяга" }, { value: "sexy", label: "Сексуальный" }, { value: "hiking", label: "Пешийтуризм" }] },
  vehicleEntering: { title: "Тип посадки", type: "selector", list: [{ value: "driver_priority", label: "Приоритет водителя" }, { value: "passenger_priority", label: "Ближайшая дверь" }, { value: "fast_priority", label: "Разные кнопки" }] },
  facialAnim: { title: "Эмоция лица", type: "selector", list: [{value:"standard",label:"Стандартный"},{value:"smug",label:"Самодовольный"},{value:"tense",label:"Напряженный"},{value:"driver",label:"Водила"},{value:"skydiver",label:"Скайдайвер"},{value:"injured",label:"Раненый"},{value:"angry",label:"Злой"},{value:"drunk",label:"Пьяный"},{value:"happy",label:"Счастливый"},{value:"pouty",label:"Дутый"},{value:"focused",label:"Сконцентрированный"},{value:"shocked1",label:"Шокированный 1"},{value:"shocked2",label:"Шокированный 2"},{value:"sleepy",label:"Сонный"},{value:"beaten",label:"Сбитый"},{value:"dead1",label:"Мертвый 1"},{value:"dead2",label:"Мертвый 2"}] },
  integratedFont: { title: "Общий шрифт", type: "selector", list: [{ value: "ProximaNova", label: "ProximaNova" }, { value: "Arial", label: "Arial" }] },
  cruiseType: { title: "Тип круиз-контроля", type: "selector", list: [{ value: "speed_limit", label: "Огран. скорости" }, { value: "adaptive", label: "Обычный" }] },
  generalSoundVol: { title: "Громкость звука", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  voiceChatVol: { title: "Громкость голосового чата игроков", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  ambientMusicVol: { title: "Громкость музыки окружения", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  animMusicVol: { title: "Громкость музыки анимаций", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  radioVol: { title: "Громкость радио", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  walkieSoundVol: { title: "Громкость рации", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  notificationVol: { title: "Уведомление о репорте", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  voiceChatBlock: { title: "Блокировка голосового чата игроков", type: "selector", list: [{ value: "no", label: "Нет" }, { value: "yes", label: "Да" }] },
  voiceChatOffDelay: { title: "Задержка отключения голосового чата", type: "selector", list: [{ value: "0", label: "0 ms" }, { value: "200", label: "200 ms" }, { value: "500", label: "500 ms" }] },
  micSensitivity: { title: "Чувствительность микрофона", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  cinemaVolume: { title: "Громкость кинотеатра", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  animMusicToggle: { title: "Музыка анимации", type: "checkbox" },
  ambientMusicToggle: { title: "Музыка окружения", type: "checkbox" },
  accessorySounds: { title: "Звуки аксессуаров", type: "checkbox" },
  navigatorVoice: { title: "Озвучка навигатора", type: "checkbox" },
  radarSound: { title: "Звук радара", type: "checkbox" },
  seatbeltWarn: { title: "Предупреждение о ремне безопасности", type: "checkbox" },
  hitmarkerSound: { title: "Звук хитмаркера", type: "checkbox" },
  listeningMode: { title: "Слух", type: "selector", list: [{ value: "standard", label: "Стандартный" }, { value: "enhanced", label: "Расширенный" }] },
  voiceActivationMode: { title: "Режим активации голосового чата", type: "selector", list: [{ value: "push", label: "По нажатию" }, { value: "voice", label: "Голосом" }] },
  noiseSuppression: { title: "Шумоподавление", type: "checkbox" },
  adminDeleteWeazelNews: { title: "Удалять Weazel News", type: "checkbox" },
  adminDeleteMarketplace: { title: "Удалять объявления", type: "checkbox" },
  adminBigChipsExchange: { title: "Обмен больших фишек", type: "checkbox" },
  adminLargeMoneyTransfer: { title: "Переводы крупных сумм", type: "checkbox" },
  adminFamilyBonus: { title: "Семейные бонусы", type: "checkbox" },
  adminMassBonus: { title: "Массовые бонусы", type: "checkbox" },
  adminCaptZoneColorChange: { title: "Смена цвета зоны захвата", type: "checkbox" },
  adminFractionBonus: { title: "Фракционные бонусы", type: "checkbox" },
  adminFractionFunding: { title: "Финансирование фракций", type: "checkbox" },
  adminCharacterAppearanceChange: { title: "Изменение внешности", type: "checkbox" },
  adminCharacterNameChange: { title: "Смена имени персонажа", type: "checkbox" },
  adminAntiCheatBan: { title: "Античит бан", type: "checkbox" },
  adminSystemShutdown: { title: "Выключение системы", type: "checkbox" },
  adminAdminLeakBan: { title: "Блокировка по утечке админов", type: "checkbox" },
  adminForbiddenAnimation: { title: "Запрет анимаций", type: "checkbox" },
  adminSuspiciousDonateActivity: { title: "Подозрительные донаты", type: "checkbox" },
  adminForbiddenSoftware: { title: "Запрет ПО", type: "checkbox" },
  adminStungunUsage: { title: "Использование тазера", type: "checkbox" },
  adminAimUsage: { title: "Использование прицела", type: "checkbox" },
  chatWidth: { title: "Ширина блока чата", type: "range", sliderOptions: { min: 200, max: 800, interval: 10 } },
  chatHeight: { title: "Высота блока чата", type: "range", sliderOptions: { min: 100, max: 800, interval: 10 } },
  chatSettings: { title: "Настройки", type: "selector", list: [{ value: "standard", label: "Стандартные" }, { value: "custom", label: "Пользовательский" }] },
  chatTheme: { title: "Тема", type: "selector", list: [{ value: "Clean", label: "Clean" }, { value: "Block", label: "Block" }] },
  chatFont: { title: "Шрифт", type: "selector", list: [{ value: "ProximaNova", label: "Proxima Nova" }, { value: "ProximaNova-Condensed", label: "PNova Condensed" }, { value: "ProximaNova-ExtraCondensed", label: "PNova ExtraCondensed" }, { value: "San-Francisco", label: "San Francisco" }] },
  chatFontStyle: { title: "Начертание", type: "selector", list: [{ value: "Light", label: "Light" }, { value: "Regular", label: "Regular" }, { value: "Semibold", label: "Semibold" }, { value: "Bold", label: "Bold" }] },
  chatBorderType: { title: "Тип внешней границы", type: "selector", list: [{ value: "Stroke", label: "Обводка" }, { value: "Shadow", label: "Тень" }] },
  chatTimestamp: { title: "Время в чате", type: "selector", list: [{ value: "No", label: "Нет" }, { value: "Time", label: "Время" }, { value: "DateTime", label: "Дата и время" }] },
  chatFontSize: { title: "Размер шрифта", type: "range", sliderOptions: { min: 12, max: 30, interval: 1 } },
  chatFontShadow: { title: "Размер тени", type: "range", sliderOptions: { min: 0, max: 10, interval: 1 } },
  chatFontShadowAlpha: { title: "Прозрачность тени", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  chatLinesMargin: { title: "Отступ между сообщениями", type: "range", sliderOptions: { min: 0, max: 100, interval: 1 } },
  chatLineHeight: { title: "Мех строчное расстояние", type: "range", sliderOptions: { min: 0, max: 10, interval: 1 } },
  chatCmdsSettings: { title: "Настройки быстрых команд", type: "selector", list: [{ value: "standard", label: "Стандартные" }, { value: "custom", label: "Пользовательский" }] },
  chatCmdsFont: { title: "Шрифт быстрых команд", type: "selector", list: [{ value: "ProximaNova", label: "ProximaNova" }, { value: "Arial", label: "Arial" }] },
  chatCmdsFontStyle: { title: "Начертание команд", type: "selector", list: [{ value: "Light", label: "Light" }, { value: "Regular", label: "Regular" }, { value: "Semibold", label: "Semibold" }, { value: "Bold", label: "Bold" }] },
  chatCmdsFontSize: { title: "Размер шрифта команд", type: "range", sliderOptions: { min: 10, max: 24, interval: 1 } },
  phone: { title: "Телефон", type: "keyBind", default: ["K"] },
  table: { title: "Таблица", type: "keyBind", default: ["Tab"] },
  pressI: { title: "Нажать I", type: "keyBind", default: ["I"] },
  voice: { title: "Голосовой чат", type: "keyBind", default: ["V"] },
  radio: { title: "Рация", type: "keyBind", default: ["R"] },
  partyCreateMarker: { title: "Создать маркер группы", type: "keyBind", default: ["B"] },
  fingerPointing: { title: "Указание пальцем", type: "keyBind", default: ["G"] },
  mainMenu: { title: "Главное меню", type: "keyBind", default: ["F5"] },
  tasksMenu: { title: "Меню задач", type: "keyBind", default: ["F6"] },
  reportMenu: { title: "Меню репорта", type: "keyBind", default: ["F7"] },
  openGarageInfo: { title: "Информация гаража", type: "keyBind", default: ["G"] },
  circleAnimMenu: { title: "Меню анимаций", type: "keyBind", default: ["H"] },
  langWheel: { title: "Языковое колесо", type: "keyBind", default: ["L"] },
  acceptRequest: { title: "Принять запрос", type: "keyBind", default: ["Y"] },
  denyRequest: { title: "Отклонить запрос", type: "keyBind", default: ["N"] },
  pickupItem: { title: "Подобрать предмет", type: "keyBind", default: ["E"] },
  takeItemFromHands: { title: "Взять предмет из рук", type: "keyBind", default: ["F"] },
  interaction: { title: "Взаимодействие", type: "keyBind", default: ["E"] },
  pressE: { title: "Нажать E", type: "keyBind", default: ["E"] },
  driverEnter: { title: "Войти водителем", type: "keyBind", default: ["F"] },
  passengerEnter: { title: "Войти пассажиром", type: "keyBind", default: ["Shift", "F"] },
  toggleEngine: { title: "Запустить двигатель", type: "keyBind", default: ["M"] },
  carLock: { title: "Заблокировать авто", type: "keyBind", default: ["L"] },
  belt: { title: "Ремень безопасности", type: "keyBind", default: ["Shift", "B"] },
  gps: { title: "GPS", type: "keyBind", default: ["G"] },
  cruise: { title: "Круиз-контроль", type: "keyBind", default: ["C"] },
  autopilot: { title: "Автопилот", type: "keyBind", default: ["Shift", "C"] },
  cuff: { title: "Надеть наручники", type: "keyBind", default: ["Ctrl", "C"] },
  followPlayer: { title: "Следовать за игроком", type: "keyBind", default: ["F"] },
  hookCuffedPlayer: { title: "Подцепить скованного", type: "keyBind", default: ["Ctrl", "H"] },
  recording: { title: "Запись", type: "keyBind", default: ["F10"] },
  changeVisorState: { title: "Изменить козырёк", type: "keyBind", default: ["U"] },
  megaphone: { title: "Мегафон", type: "keyBind", default: ["O"] },
  crouch: { title: "Присесть", type: "keyBind", default: ["Ctrl"] },
  crawl: { title: "Ползти", type: "keyBind", default: ["X"] },
  OOCMode: { title: "OOC режим", type: "keyBind", default: ["T"] },
  pressF: { title: "Нажать F", type: "keyBind", default: ["F"] },
  clothesAction: { title: "Действие с одеждой", type: "keyBind", default: ["A"] },
  cancelMacro: { title: "Отменить макрос", type: "keyBind", default: ["Esc"] },
  muteMicrophone: { title: "Отключить микрофон", type: "keyBind", default: ["Shift", "M"] },
  crosshairSettings: { title: "Настройки", type: "selector", list: [{ value: "standard", label: "Стандартные" }, { value: "custom", label: "Пользовательский" }] },
  crosshairColor: { title: "Цвет прицела", type: "colorPicker", default: { "Основной": "#ffffff", "Наведение": "#ff0000" } },
  crosshairCenter: { title: "Центр", type: "selector", list: [{ value: "no", label: "Нет" }, { value: "small", label: "Маленький" }, { value: "large", label: "Большой" }] },
  crosshairCentralDistance: { title: "Расстояние от центра", type: "range", sliderOptions: { min: 0, max: 20, interval: 1 } },
  crosshairLineLength: { title: "Длина линий", type: "range", sliderOptions: { min: 0, max: 50, interval: 1 } },
  crosshairLineThickness: { title: "Толщина линий", type: "range", sliderOptions: { min: 1, max: 10, interval: 1 } },
  crosshairIncline: { title: "Наклон", type: "range", sliderOptions: { min: 0, max: 90, interval: 1 } },
  crosshairStroke: { title: "Толщина обводки", type: "range", sliderOptions: { min: 0, max: 10, interval: 1 } },
  crosshairOpacity: { title: "Прозрачность", type: "range", sliderOptions: { min: 0, max: 1, interval: 0.1 } },
  // Добавь в объект meta:

telegramActivity: { title: "Подробительная активность", type: "checkbox" },
telegramRules: { title: "Получение наказаний", type: "checkbox" },
telegramAttack: { title: "Контроль территорий (Банды)", type: "checkbox" },
territoryAttack: { title: "Контроль территорий (Семьи)", type: "checkbox" },
telegramPersonalHouse: { title: "Налог на дом (личный) за 1-7 дней до конфискации", type: "checkbox" },
telegramFamilyHouse: { title: "Налог на дом (семейный) за 1-7 дней до конфискации", type: "checkbox" },
telegramFamilyOffice: { title: "Налог на офис (семейный) за 1-7 дней до конфискации", type: "checkbox" },
telegramFamilyStorage: { title: "Налог на склад (семейный) за 1-7 дней до конфискации", type: "checkbox" },
telegramApartment: { title: "Налог на квартиру за 1-7 дней до конфискации", type: "checkbox" },
telegramBusiness: { title: "Налог на бизнес за 1-7 дней до конфискации", type: "checkbox" },
telegramVictory: { title: "Победа на аукционе", type: "checkbox" },
telegramSale: { title: "Продажа предмета", type: "checkbox" },
telegramBid: { title: "Ставка перебита", type: "checkbox" },
telegramStock: { title: "Новые котировки", type: "checkbox" },
rentalTransport: { title: "Сдача транспорта в аренду", type: "checkbox" },
rentalReturn: { title: "Возврат транспорта с аренды", type: "checkbox" },
};

export function getSettingItem(key) {
  return meta[key] ?? null;
}

export function getSettingValue(key) {
  let val;
  const unsubscribe = storeSettings.subscribe(v => {
    val = v?.[key] !== undefined ? v[key] : defaultSettings[key];
  });
  unsubscribe();
  return val;
}

export function updateSettingValue(key, value) {
  storeSettings.update(v => ({
    ...v,
    [key]: value
  }));
}